### ISSUE TITLE
ErrorCodeIOException on ubuntu jaunty. any idea?

### ISSUE THREAD

**Issue by wiemann** [akaihola/unoconv#1]
Hi, 
I installed oo headless on jaunty, but unoconv won't work. Any idea?

unoconv: UnoException during conversion in <class '__main__.com.sun.star.task.ErrorCodeIOException'>: 
ERROR: The provided document cannot be converted to the desired format. (code: 1287)

**Comment by dagwieers** [comment]
Please look at the following threads:

http://user.services.openoffice.org/en/forum/viewtopic.php?f=20&t=25308
http://www.openoffice.org/issues/show_bug.cgi?id=107448

It seems to be an issue with creating PDF's with multiple requests to a single listener. It might help to start and stop the listener between conversions. Definitely an OpenOffice problem :-/
