### ISSUE TITLE
PDF does not preserve font even after using SelectPdfVersion=1

### ISSUE THREAD

**Issue by cmnajs** [akaihola/unoconv#2]
I am converting ms word doc file to pdf using unoconv. I am facing a problem that it does not preserve original fonts used in doc file instead replace them with some equivalent fonts. How can I solve this issue.

**Comment by akaihola** [comment]
That is an OpenOffice/LibreOffice issue. Unoconv just instructs the office suite to save the document as a PDF. Please try to do the same in the office suite GUI and verify that the font problem occurs there, too.

**Comment by cmnajs** [comment]
It do the same using GUI, so its open office not unoconv
